name: Test Application
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.1.app
      - name: Fix plugins
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
      - run: tuist install
      - run: tuist test Cork
